### ISSUE TITLE
'list' object has no attribute 'get_repos_docs_detail'

### ISSUE THREAD

**Issue by Andln** [Xarrow/simple-pyyuque#1]
andln = yq.SimplePyYuQueAPI(token="token", app_name="py_yuque1")
andln_doc = andln.Doc()

Traceback (most recent call last):
  File "yuque.py", line 21, in <module>
    andln_doc_detial = andln_doc.get_repos_docs_detail(namespace="xxx", slug="xxx").base_response
AttributeError: 'list' object has no attribute 'get_repos_docs_detail'

'list' object has no attribute 'get_repos_docs_detail'

请问这个问题是什么问题

**Comment by Xarrow** [comment]
> andln = yq.SimplePyYuQueAPI(token="token", app_name="py_yuque1")
> andln_doc = andln.Doc()
> 
> Traceback (most recent call last):
> File "yuque.py", line 21, in 
> andln_doc_detial = andln_doc.get_repos_docs_detail(namespace="xxx", slug="xxx").base_response
> AttributeError: 'list' object has no attribute 'get_repos_docs_detail'
> 
> 'list' object has no attribute 'get_repos_docs_detail'
> 
> 请问这个问题是什么问题

这个报错应该是 `andln_doc` 返回成一个 `list`类型了。

1.  `yq.SimplePyYuQueAPI` 是一个类， 而不是一个方法。  你可以按照文档上的写法试一下

```python
doc_api = SimplePyYuQueAPI(token="token", app_name="py_yuque1").Doc()
doc_api.get_repos_docs_detail(namespace="ns", slug="slug").base_response
```

2. 你可以使用  `get_user` 查看下是否授权成功。

```python
 user_api = SimplePyYuQueAPI(token="token", app_name="py_yuque1").User()
 print(user_api.get_user())
 print(user_api.user)
```
3. 我本地环境测试了下是可以正常的运行的，如下是我的结果，

```
{'id': 1057879, 'slug': 'randomstring', 'title': '测试更新', 'book_id': 189411, 'user_id': 104023, 'format': 'markdown', 'body': '你好世界! (修改body)', 'body_draft': '', 'body_html': '<p>你好世界! (修改body)</p>\n', 'public': 1, 'status': 1, 'likes_count': 0, 'comments_count': 0, 'content_updated_at': '2018-12-16T08:57:29.000Z', 'deleted_at': None, 'created_at': '2018-12-16T08:48:01.000Z', 'updated_at': '2019-01-05T10:50:47.000Z', 'published_at': '2019-01-05T10:50:47.075Z', 'first_published_at': None, 'word_count': 7, 'cover': None, 'description': '你好世界! (修改body)', 'custom_description': None, 'creator': None, 'book': None, '_serializer': 'v2.doc_detail'} 
```

4. 如果上面方法还是没有解决的话， 还请贴出完整的代码排查 , :blush:
